---
databases: []
pg_port: 5432
max_connections: 200
shared_buffers: 1GB
effective_cache_size: 3GB
work_mem: 5242kB
maintenance_work_mem: 256MB
min_wal_size: 1GB
max_wal_size: 2GB
checkpoint_completion_target: 0.7
wal_buffers: 16MB
default_statistics_target: 100
