- name: Configura usuário padrão
  user:
    name: odoo
    uid: 1040
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{user_odoo_password}}"

- name: Permite ssh no firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Permite http no firewall
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8090
    jump: ACCEPT

- name: Bloqueia o restante das conexoes
  iptables:
    chain: INPUT
    jump: DROP
    state: absent

- name: Check if swap file exists
  stat:
    path: "{{swap_file_path}}"
    get_checksum: False
    get_md5: False
  register: swap_file_check
  tags:
    - swap.file.check

- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_kb }}k
           creates="{{ swap_file_path }}"
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.create

- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.permissions

- name: "Check swap file type"
  command: file {{ swap_file_path }}
  register: swapfile
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.mkswap

- name: Make swap file
  command: "mkswap {{ swap_file_path }}"
  when: not swap_file_check.stat.exists and swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=none
      src={{ swap_file_path }}
      fstype=swap
      opts=sw
      passno=0
      dump=0
      state=present
  tags:
    - swap.fstab

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: not swap_file_check.stat.exists
  tags:
    - swap.file.swapon

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{swappiness}}"
  tags:
    - swap.set.swappiness

- name: Instalando Certbot
  apt:
      name: software-properties-common
      state: present

- apt_repository:
    repo: ppa:certbot/certbot
    state: present

- apt:
    name: python-certbot-nginx
    state: present
