---
- name: Install correct version docker-py to avoid problems
  pip: name=docker-py version=1.9.0
- name: pull docker odoo
  docker_image:
      name: trustcode/docker-odoo:v11

- name: Configura usuario padrao
  user:
      name: odoo
      groups: docker
      append: yes
